const products = [
    {id: 1,
    nombre: "El aleph",
    autor: "Jorge Luis Borges",
    pags: "216 páginas",
    precio: 4449,
    genero: "Cuento",
    img: "/img/ElAleph.jpg",
    sintesis: 'Con excepción de "Emma Zunz" y de "Historia del guerrero y de la cautiva", los cuentos de este libro aparecido cinco años después de Ficciones pertenecen al género fantástico: "El inmortal" explora el efecto que la inmortalidad causaría en los hombres; "Los teólogos" es un sueño melancólico sobre la identidad personal; "Biografía de Tadeo Isidoro Cruz", una glosa del Martín Fierro; "La otra muerte", una fantasía sobre el tiempo; "Deutsches Requiem", un intento de entender el destino trágico alemán. El cuento "El Aleph" -publicado por primera vez en 1945 y que en 1949 dio nombre al libro- aborda uno de los temas recurrentes en la literatura de Borges: el infinito. Porque en esa esfera resplandeciente confluyen de un modo asombroso todos los tiempos y todos los espacios.'
    },

    {id: 2,
    nombre: "Ficciones",
    autor: "Jorge Luis Borges",
    pags: "180 páginas",
    precio: 4449,
    genero: "Cuento",
    img: "/img/Ficciones.jpg",
    sintesis: 'Ficciones, compuesta por los libros El jardín de senderos que se bifurcan (1941) y Artificios (1944), es posiblemente la obra más reconocida de Jorge Luis Borges y sin duda un hito en la historia de la literatura. Aquí se encuentran lo policial ("La muerte y la brújula") y lo fantástico ("La lotería en Babilonia"), lo irreal ("Las ruinas circulares") y lo imaginario ("Tlön, Uqbar, Orbis Tertius"), el que Borges consideró acaso su mejor cuento ("El Sur") y el que cientos de miles de lectores han consagrado como uno de los más cautivantes?comienzos de un relato jamás escrito ("Nadie lo vio desembarcar en la unánime noche..."). Cada uno de los dieciséis cuentos reunidos en este libro es, en sí, pieza fundacional y celebración del universo borgeano.',
    },

    {id: 3,
    nombre: "Inquisiciones/Otras inquisiciones",
    autor: "Jorge Luis Borges",
    pags: "480 páginas",
    precio: 5449,
    genero: "Ensayo",
    img: "/img/Inquisiciones.jpg",
    sintesis: 'Borges publica Inquisiciones en 1925, mucho antes de ser considerado una de las voces más importantes de la literatura mundial. Sin embargo, en esos primeros ensayos se encuentra el repertorio de temas recurrentes en su obra posterior, especialmente en Otras inquisiciones (1952): el potencial literario de las ideas metafísicas, el yo como simulacro, las tradiciones hispánica y anglosajona, el criollismo, los cruces entre lectura y escritura, el idioma, el tiempo, los espejos.',
    },

    {id: 4,
    nombre: "Historia de la eternidad",
    autor: "Jorge Luis Borges",
    pags: "176 páginas",
    precio: 2799,
    genero: "Ensayo",
    img: "/img/HistoriaEternidad.jpg",
    sintesis: 'Publicado en 1936, Historia de la eternidad, volumen de ensayos en el que aparecen prefigurados el genio y la imaginación que Borges desplegará en el siguiente medio siglo de obra, incluye, entre otros, los célebres "La doctrina de los ciclos", "El tiempo circular", "La metáfora", "Los traductores de "Las mil y una noches" y "El acercamiento a Almotásin".',
    },

    {id: 5,
    nombre: "La rosa profunda",
    autor: "Jorge Luis Borges",
    pags: "72 páginas",
    precio: 2949,
    genero: "Poesía",
    img: "/img/RosaProfunda.jpg",
    sintesis: 'En su prólogo a La rosa profunda, Borges escribe: "Dos deberes tendría todo verso: comunicar un hecho preciso y tocarnos físicamente, como la cercanía del mar". Llevando a la práctica la teoría, los más de treinta poemas aquí reunidos hacen palpables las espadas y las máscaras, los espejos y las sombras, los libros y los contornos imprecisos de las cosas invisibles al ojo ciego; temas y motivos a los que el autor vuelve con insistencia a lo largo de toda su obra y que configuran su universo literario.',
    },

    {id: 6,
    nombre: "La cifra",
    autor: "Jorge Luis Borges",
    pags: "96 páginas",
    precio: 2949,
    genero: "Poesía",
    img: "/img/LaCifra.jpg",
    sintesis: 'Publicado por primera vez en 1981, La cifra, volumen de poesía en el que aparecen desplegados el genio y la imaginación del Borges maduro y reflexivo que ha alcanzado fama mundial, incluye, entre otros, los célebres "La fama", "Nostalgia del presente", "Eclesiatés, I, 9", "Los justos", "Milonga de Juan Muraña", "Buenos Aires".',
    },

    {id: 7,
    nombre: "Los conjurados",
    autor: "Jorge Luis Borges",
    pags: "88 páginas",
    precio: 2949,
    genero: "Poesía",
    img: "/img/Conjurados.jpg",
    sintesis: 'Publicado por primera vez en 1985, un año antes de su muerte, Los conjurados incluye cuarenta y cuatro poemas y prosas poéticas que Borges asegura tuvieron su origen en sueños. El que da título al libro profetiza la concordia y hermandad entre los hombres, tal vez su último deseo.',
    },

    {id: 9,
    nombre: "La moneda de hierro",
    autor: "Jorge Luis Borges",
    pags: "72 páginas",
    precio: 2949,
    genero: "Poesía",
    img: "/img/MonedaHierro.jpg",
    sintesis: 'Publicado por primera vez en 1976, ya instalada la dictadura militar en la Argentina, La moneda de hierro incluye treinta y seis poemas, sonetos en su mayoría, que revelan un nuevo giro de impronta onírica en la poesía de un Borges que advierte será juzgado por la imagen que se tiene de él antes que por el contenido de su libro.',
    },

    {id: 10,
    nombre: "Siete noches",
    autor: "Jorge Luis Borges",
    pags: "192 páginas",
    precio: 2949,
    genero: "Entrevistas/Conferencias",
    img: "/img/SieteNoches.jpg",
    sintesis: 'Siete memorables conferencias dictadas por Borges en el Teatro Coliseo de Buenos Aires durante los meses de junio, julio y agosto de 1977.'
    },

    {id: 11,
    nombre: "Borges: el misterio esencial",
    autor: "Jorge Luis Borges",
    pags: "320 páginas",
    precio: 4449,
    genero: "Entrevistas/Conferencias",
    img: "/img/MisterioEsencial.jpg",
    sintesis: 'Ya en sus ochenta años y convertido en una personalidad de enorme notoriedad pública a nivel mundial, Borges emprende un viaje a diversas universidades de los Estados Unidos en las que mantiene conversaciones entrañables sobre sí, sus mundos y sus obras, con académicos, periodistas y público general.',
    },

    {id: 12,
    nombre: "El tango",
    autor: "Jorge Luis Borges",
    pags: "160 páginas",
    precio: 2949,
    genero: "Entrevistas/Conferencias",
    img: "/img/Tango.jpg",
    sintesis: 'Cincuenta años después de pronunciadas, cuatro conferencias inéditas de Borges sobre el tango que abordan, a puro ingenio, desde sus orígenes en los arrabales de la Buenos Aires de antaño, sus raíces en la milonga y sus personajes (compadritos, "niños bien", mujeres de mala vida), hasta la figura de Carlos Gardel, el espíritu del "tango llorón", y el lugar del gaucho y las "casas malas" en su lírica.',
    },

    {id: 13,
    nombre: "Alias",
    autor: "Jorge Luis Borges y Adolfo Bioy Casares",
    pags: "480 páginas",
    precio: 5149,
    genero: "En colaboración",
    img: "/img/Alias.jpg",
    sintesis: 'Este volumen reúne la obra completa en colaboración que Borges y Bioy Casares publicaron con sus nombres propios y con los alias H. Bustos Domecq y B. Suárez Lynch. '},

    {id: 14,
    nombre: "Los mejores cuentos policiales",
    autor: "Jorge Luis Borges y Adolfo Bioy Casares",
    pags: "504 páginas",
    precio: 5449,
    genero: "En colaboración",
    img: "/img/MejoresPoliciales.jpg",
    sintesis: 'Jorge Luis Borges y Adolfo Bioy Casares, amigos por más de cincuenta años, compartieron a lo largo de sus vidas una pasión: el género policial. Originalmente publicada en dos volúmenes, la selección de treinta y un textos que reunieron en Los mejores cuentos policiales celebra su amistad y su gusto por el género.'},

    {id: 15,
        nombre: "Qué es el budismo",
        autor: "Jorge Luis Borges y Alicia Jurado",
        pags: "128 páginas",
        precio: 2849,
        genero: "En colaboración",
        img: "/img/Budismo.jpg",
        sintesis: 'El budismo, rama de la filosofía, ocupa un lugar central en el conjunto de la obra de Borges. La percepción del cosmos como un laberinto o una paradoja, la negación del Yo, el cuestionamiento a la concepción occidental del tiempo y la singular noción de que el mundo es una ficción y la realidad un sueño, entre otras ideas, cruzan los ensayos, cuentos y poemas del autor desde sus textos más tempranos y son la particular reformulación con fines literarios de algunos de los nodos centrales de esta doctrina.'},
    
]

export {products}