const products = [
    {id: 1,
    nombre: "El aleph",
    autor: "Jorge Luis Borges",
    pags: "160 páginas",
    precio: 3649,
    genero: "Cuento",
    img: "/public/img/ElAleph.jpg",
    },

    {id: 2,
    nombre: "Ficciones",
    autor: "Jorge Luis Borges",
    pags: "180 páginas",
    precio: 3349,
    genero: "Cuento",
    img: "/public/img/Ficciones.jpg",
    },

    {id: 3,
    nombre: "Inquisiciones/Otras inquisiciones",
    autor: "Jorge Luis Borges",
    pags: "250 páginas",
    precio: 3999,
    genero: "Ensayo",
    img: "/public/img/Inquisiciones.jpg",
    },

    {id: 4,
    nombre: "Historia de la eternidad",
    autor: "Jorge Luis Borges",
    pags: "170 páginas",
    precio: 2499,
    genero: "Ensayo",
    img: "/public/img/HistoriaEternidad.jpg",
    },

    {id: 5,
    nombre: "La rosa profunda",
    autor: "Jorge Luis Borges",
    pags: "120 páginas",
    precio: 2999,
    genero: "Poesía",
    img: "/public/img/RosaProfunda.jpg",
    },

    {id: 6,
    nombre: "La cifra",
    autor: "Jorge Luis Borges",
    pags: "130 páginas",
    precio: 2999,
    genero: "Poesía",
    img: "/public/img/LaCifra.jpg",
    }
]

export {products}